Pages/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using WebbshoppenSS.Models;
using System.Linq;
using WebbshoppenSS.Data;


namespace WebbshoppenSS.Pages
{
    public class CartModel : PageModel
    {
        public List<Product> GetShoppingCarts { get; set; }

        [BindProperty]
        public int Shipping { get; set; }


        public void OnGet()
        {
            GetShoppingCarts = ShoppingCart.GetShoppingCart();
            GetShoppingCarts.OrderBy(m => m.ProductID).ToList();

        }

        public IActionResult OnPostAdd(int id)
        {

            ShoppingCart.AddToCart(id);

            return RedirectToPage("/Cart");

        }

        public IActionResult OnPostRemove(int id)
        {

            ShoppingCart.RemoveFromCart(id);

            return RedirectToPage("/Cart");

        }

        public void OnPostAdressShipping()
        {
            GetShoppingCarts = ShoppingCart.GetShoppingCart();

            var ship = Request.Form["shipping"];

            ViewData["confirmation"] = $"{ship}";

            //return RedirectToPage("/Cart");

        }

        public IActionResult OnPostBuy()
        {
            GetShoppingCarts = ShoppingCart.GetShoppingCart();
            GetShoppingCarts.Clear();
            

            return RedirectToPage("/OrderComplete");

        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace WebbshoppenSS.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Future.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using WebbshoppenSS.Models;
using System.Linq;
using WebbshoppenSS.Data;


namespace WebbshoppenSS.Pages
{
    public class FutureModel : PageModel
    {
        public List<FutureAge> ProductsHeavy { get; set; }
        public void OnGet()
        {
            ProductsHeavy = ProductHeavy.GetProductsHeavy();
            ProductsHeavy.OrderBy(m => m.ProductID).ToList();
        }

        public IActionResult OnPost(int id)
        {

            ShoppingCart.AddToCart(id);

            return RedirectToPage("/Future");

        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebbshoppenSS.Models;
using WebbshoppenSS.Data;
using System.Collections;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebbshoppenSS.Pages
{
    public class IndexModel : PageModel
    {
        public List<Product> Alla { get; set; }
        public IEnumerable<Product> GetFeatured { get; set; }

        [BindProperty(SupportsGet = true)]
        public string SearchString { get; set; }

        public void OnGet(bool IsChecked)

        {
            Alla = AllProducts.GetAllProducts();

                var products = from m in AllProducts.Products
                             select m;
                if (!string.IsNullOrEmpty(SearchString))
                {
                    products = products.Where(s => s.Name.Contains(SearchString));
                }

                Alla = products.ToList();

            GetFeatured = Alla.Where(x => x.Featured == true);

        }

        public IActionResult OnPost(int id)
        {

            ShoppingCart.AddToCart(id);

            return RedirectToPage("/Cart");

        }
    }
}

Pages/OrderComplete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebbshoppenSS.Pages
{
    public class OrderCompleteModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Past.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using WebbshoppenSS.Models;
using System.Linq;
using WebbshoppenSS.Data;

namespace WebbshoppenSS.Pages
{
    public class PastModel : PageModel
    {
        public List<MiddleAge> ProductsLight { get; set; }

        public void OnGet(int add)
        {
            ProductsLight = ProductLight.GetProductsLight();
            ProductsLight = ProductsLight.OrderBy(m => m.ProductID).ToList();
        }

        public IActionResult OnPost(int id)
        {

            ShoppingCart.AddToCart(id);

            return RedirectToPage("/Past");

        }


    }
}

Pages/Present.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using WebbshoppenSS.Models;
using System.Linq;
using WebbshoppenSS.Data;


namespace WebbshoppenSS.Pages
{
    public class PresentModel : PageModel
    {
        public List<NowAge> ProductsMedium { get; set; }
        public void OnGet()
        {
            ProductsMedium = ProductMedium.GetProductsMedium();
            ProductsMedium.OrderBy(m => m.ProductID).ToList();
        }

        public IActionResult OnPost(int id)
        {

            ShoppingCart.AddToCart(id);

            return RedirectToPage("/Present");

        }

    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebbshoppenSS.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/ViewAll.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebbshoppenSS.Data;
using WebbshoppenSS.Models;

namespace WebbshoppenSS.Pages
{
    public class ViewAllModel : PageModel
    {
        public List<Product> GetAllProducts { get; set; }
        public List<Product> Result { get; set; }

        [BindProperty(SupportsGet = true)]
        public string SearchString { get; set; }



        public void OnGet()
        {
            GetAllProducts = Data.AllProducts.GetAllProducts();
            Result = GetAllProducts.OrderBy(m => m.ProductID).ToList();

            var products = from m in AllProducts.Products
                           select m;
            if (!string.IsNullOrWhiteSpace(SearchString))
            {
                products = products.Where(s => s.Name.ToLower().Contains(SearchString));
            
            }

            Result = products.ToList();
        }

        public IActionResult OnPost(int id)
        {

            ShoppingCart.AddToCart(id);

            return RedirectToPage("/ViewAll");

        }

    }
}

Pages/Cart.cshtml
@page
@model WebbshoppenSS.Pages.CartModel
@{
    double sum = 0;
    int shippingOne = 29;
    int shippingTwo = 99;
}
<h1 class="text-center">Shopping Cart</h1>
<br />
<table class="table">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Type</th>
            <th scope="col">Price</th>
            <th scope="col">Amount</th>
        </tr>

    </thead>

    @foreach (var item in Model.GetShoppingCarts)
    {


        <tbody>
            <tr>
                <th scope="row">@item.ProductID </th>
                <td>@item.Name</td>
                <td>@item.ProductType</td>
                <td>EUR: @item.Price / SEK: @(item.PriceSek = item.Price * 9.5 )</td>
                <td>Amount: @item.Amount</td>
                <td>
                    <form method="post">
                        <div class="mb-3">
                            <button class="btn btn-primary" type="submit" asp-page-handler="Add" asp-route-id="@item.ProductID">Add</button>
                            <button class="btn btn-primary" type="submit" asp-page-handler="Remove" asp-route-id="@item.ProductID">Remove</button>
                        </div>
                    </form>
                </td>

            </tr>
        </tbody>
        sum += item.Price;
    }
</table>


<h2 class="text-center">TOTAL PRICE: @sum €</h2>
<br />
<h3>Shipping info</h3>
<br />
<form method="post">
    <div class="form-group row">
        <label for="inputName" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="inputName" placeholder="Full name" required>
        </div>
    </div>
    <div class="form-group row">
        <label for="inputEmail" class="col-sm-2 col-form-label">Email</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="inputEmail" placeholder="Email" required>
        </div>
    </div>
    <div class="form-group row">
        <label for="inputStreet" class="col-sm-2 col-form-label">Street Address</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="inputStreet" placeholder="Street" required>
        </div>
    </div>
    <div class="form-group row">
        <label for="inputPostal" class="col-sm-2 col-form-label">Postal Code</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="inputStreet" placeholder="Postal Code" required>
        </div>
    </div>
    <div class="form-group row">
        <label for="inputCity" class="col-sm-2 col-form-label">City</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="inputCity" placeholder="City" required>
        </div>
    </div>


    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-2 pt-0">Shipping</legend>
            <div class="col-sm-10">
                <div class="form-check">
                    <input type="radio" name="shipping" value="@shippingOne" checked="checked" />
                    <label class="form-check-label" for="gridRadios1">
                        Normal Shipping: @shippingOne €
                    </label>
                </div>
                <div class="form-check">
                    <input type="radio" name="shipping" value="@shippingTwo" />
                    <label class="form-check-label" for="gridRadios2">
                        Express Shipping: @shippingTwo €
                    </label>
                </div>
            </div>
        </div>
    </fieldset>

    <div class="mb-3">
        <button class="btn btn-primary" type="submit" asp-page-handler="AdressShipping">Accept Shipping</button>
    </div>
</form>
<br />

<h3>Price with shipping: @(sum + Model.Shipping) €</h3>
<h4>Without VAT: @(Math.Round(((sum + Model.Shipping) * 0.8), 2)) €</h4>


<br />
<br />
<form method="post">
    <div class="col-4">
        <div class="row">
            <h3>Payment Method:</h3>
        </div>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1" checked="checked">
        <label class="form-check-label" for="flexRadioDefault1">
            CreditCard
        </label>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2">
        <label class="form-check-label" for="flexRadioDefault2">
            PayPal
        </label>
    </div>
    <br />
    <div class="mb-3">
        <button class="btn btn-success btn-lg" type="submit" asp-page-handler="Buy">Place Order</button>
    </div>
</form>

Pages/Future.cshtml
@page
@model WebbshoppenSS.Pages.FutureModel
@{
}

<h1>The Future</h1>
<br />

<table class="table">
	<thead>
		<tr>
			<th scope="col">ID</th>
			<th scope="col">Name</th>
			<th scope="col">Price</th>
			<th scope="col">Type</th>
			<th scope="col">Stock</th>
			<th scoope="col">Category</th>
		</tr>

	</thead>
	@foreach (var item in Model.ProductsHeavy)

	{
		<tbody>
            <tr>
                <th scope="row">@item.ProductID <img src="~/img/@item.ImgUrl" width="40" height="40" />  </th>
                <td>@item.Name</td>
                <td>EUR: @item.Price / SEK: @(item.PriceSek = item.Price * 9.5 )</td>
                <td>@item.ProductType</td>
                <td>@item.Quanity</td>
                @foreach (var category in item.ProductCategory)
                {
                    <td> @category</td>
                }

                <td>
                    <form method="post">
                        <div class="mb-3">
                            <button class="btn btn-primary" type="submit" asp-route-id="@item.ProductID">Buy</button>
                        </div>
                    </form>
                </td>
            </tr>
			<tr>
				<td>
					<p>

						<button class="btn btn-secondary btn-sm" type="button" data-toggle="collapse" data-target="#@item.Name.Replace(" ", "")" aria-expanded="false" aria-controls="collapseExample">
							More info
						</button>
					</p>
					<div class="collapse" id="@item.Name.Replace(" ", "")">
						<div class="card card-body" style="width: 18rem;">
							<img src="~/img/@item.ImgUrl" class="card-img-top" />
							<p class="card-text">@item.Details</p>
							<p class="card-text">@(item.Interplanetary ? "Can be moved between planets" : "Earth based")</p>
						</div>
					</div>
				</td>
			</tr>
		</tbody>

	}

</table>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<!--
<div class="container justify-content-sm-center">

<div class="jumbotron" style="margin-top: -2rem; margin-left:-15rem; margin-right: -15rem;
        padding: 9.2rem; padding-left: 1rem; padding-right: 1rem;  background-image: url(img/thumbinal.jpg)">

</div>
</div>
     -->
<img src="~/img/thumbinal.jpg" class="img-fluid" alt="Responsive image" style="padding: 0 0 0 0">


<h1 class="text-center">Welcome to our shop</h1>
<br />

<div class="row justify-content-around" >


    @foreach (var item in Model.GetFeatured)
    {
        <div class="card" style="width:20em; margin:10px;">
            <a asp-page="">
                <img src="~/img/@item.ImgUrl" class="card-img-top" style="width:20rem; height:30rem;">
            </a>

            <div class="card-body">
                <h3 class="card-title">@item.Name</h3>
                <h5 class="card-title">Unit: @item.ProductType</h5>
                @foreach (var category in item.ProductCategory)
                {
                    <h5 class="card-title">Type: @category</h5>
                }
                <h5 class="card-text"> Price: @item.Price&euro; (SEK: @(item.Price * 9.5))</h5>
                <p class="card-text">In Stock: @item.Quanity</p>
            </div>
            <div class="card-footer">

                <!-- <a class="btn btn-info" asp-page="">Details</a>-->
                <p>
                    <button class="btn btn-info" type="button" data-toggle="collapse" data-target="#@item.Name.Replace(" ", "")" aria-expanded="false" aria-controls="collapseExample">
                        Details
                    </button>
                </p>
                <div class="collapse" id="@item.Name.Replace(" ", "")">
                    <div class="card card-body" style="width: 18rem;">
                        <p class="card-text">@item.Details</p>
                    </div>
                </div>
                <form method="post">
                    <!--<a class="btn btn-success" asp-page="">Add to Cart</a> -->
                    <button class="btn btn-success" type="submit" asp-route-id="@item.ProductID">Add to Cart</button>
                </form>

            </div>
            <div class="card"></div>
        </div>
    }
</div>

Pages/OrderComplete.cshtml
@page
@model WebbshoppenSS.Pages.OrderCompleteModel
@{
}

<div class="card">
  <h5 class="card-header">Thank you for your order!</h5>
  <div class="card-body">
    <h5 class="card-title">Your products will be shipped to you soon</h5>
    <p class="card-text">If you have any questions email us at <a href="#">notascam@totallyascam.org</a></p>
    <a asp-page="/Index" class="btn btn-primary">To Homepage</a>
  </div>
</div>

Pages/Past.cshtml
@page
@model WebbshoppenSS.Pages.PastModel
@{
}

<h1>The Past</h1>
<br />

<table class="table">
	<thead>
		<tr>
			<th scope="col">ID</th>
			<th scope="col">Name</th>
			<th scope="col">Price</th>
			<th scope="col">Type</th>
			<th scope="col">Stock</th>
			<th scoope="col">Category</th>
		</tr>

	</thead>
	@foreach (var item in Model.ProductsLight)

	{
		<tbody>
            <tr>
                <th scope="row">@item.ProductID <img src="~/img/@item.ImgUrl" width="40" height="40" />  </th>
                <td>@item.Name</td>
                <td>EUR: @item.Price / SEK: @(item.PriceSek = item.Price * 9.5 )</td>
                <td>@item.ProductType</td>
                <td>@item.Quanity</td>
                @foreach (var category in item.ProductCategory)
                {
                    <td> @category</td>
                }
                <td>
                <td>
                    <form method="post">
                        <div class="mb-3">
                            <button class="btn btn-primary" type="submit" asp-route-id="@item.ProductID">Buy</button>
                        </div>
                    </form>
                </td>
            </tr>
			<tr>
				<td>
					<p>

						<button class="btn btn-secondary btn-sm" type="button" data-toggle="collapse" data-target="#@item.Name.Replace( " ", "")" aria-expanded="false" aria-controls="collapseExample">
							More info
						</button>
					</p>
					<div class="collapse" id="@item.Name.Replace(" ", "")">
						<div class="card card-body" style="width: 18rem;">
							<img src="~/img/@item.ImgUrl" class="card-img-top" />
							<p class="card-text">@item.Details</p>
							<p class="card-text">@(item.HasShield ? "Has a shield" : "No shield")</p>
						</div>
					</div>
				</td>
			</tr>
		</tbody>

	}

</table>

Pages/Present.cshtml
@page
@model WebbshoppenSS.Pages.PresentModel
@{
}

<h1>The Present</h1>
<br />

<table class="table">
	<thead>
		<tr>
			<th scope="col">ID</th>
			<th scope="col">Name</th>
			<th scope="col">Price</th>
			<th scope="col">Type</th>
			<th scope="col">Stock</th>
			<th scoope="col">Category</th>
		</tr>

	</thead>
	@foreach (var item in Model.ProductsMedium)

	{
		<tbody>
            <tr>
                <th scope="row">@item.ProductID <img src="~/img/@item.ImgUrl" width="40" height="40" />  </th>
                <td>@item.Name</td>
                <td>EUR: @item.Price / SEK: @(item.PriceSek = item.Price * 9.5 )</td>
                <td>@item.ProductType</td>
                <td>@item.Quanity</td>
                @foreach (var category in item.ProductCategory)
                {
                    <td> @category</td>
                }

                <td>
                    <form method="post">
                        <div class="mb-3">
                            <button class="btn btn-primary" type="submit" asp-route-id="@item.ProductID">Buy</button>
                        </div>
                    </form>
                </td>
            </tr>
			<tr>
				<td>
					<p>

						<button class="btn btn-secondary btn-sm" type="button" data-toggle="collapse" data-target="#@item.Name.Replace(" ", "")" aria-expanded="false" aria-controls="collapseExample">
							More info
						</button>
					</p>
					<div class="collapse" id="@item.Name.Replace(" ", "")">
						<div class="card card-body" style="width: 18rem;">
							<img src="~/img/@item.ImgUrl" class="card-img-top" />
							<p class="card-text">@item.Details</p>
							<p class="card-text">@(item.LandBased ? "Land based" : "Air/Water based")</p>
						</div>
					</div>
				</td>
			</tr>
		</tbody>

	}

</table>

Pages/ViewAll.cshtml
@page
@model WebbshoppenSS.Pages.ViewAllModel
@{
}


<h1>Full Assortment</h1>
<br />

<form>
    <p>
        <input type="text" asp-for="SearchString" />
        <input type="submit" value="Search" />
    </p>
</form>

<h5>All Products:</h5>

<table class="table">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Type</th>
            <th scope="col">Stock</th>
            <th scoope="col">Category</th>

        </tr>

    </thead>
    @foreach (var item in Model.Result)

    {
        <tbody>
            <tr>
                <th scope="row">@item.ProductID <img src="~/img/@item.ImgUrl" width="40" height="40" />  </th>
                <td>@item.Name</td>
                <td>EUR: @item.Price / SEK: @(item.PriceSek = item.Price * 9.5 )</td>
                <td>@item.ProductType</td>
                <td>@item.Quanity</td>
                @foreach (var category in item.ProductCategory)
                {
                    <td> @category</td>
                }

                <td>
                    <form method="post">
                        <div class="mb-3">
                            <button class="btn btn-primary" type="submit" asp-route-id="@item.ProductID">Buy</button>
                        </div>
                    </form>
                </td>
            </tr>
            <tr>
                <td>
                    <p>

                        <button class="btn btn-secondary btn-sm" type="button" data-toggle="collapse" data-target="#@item.Name.Replace(" ", "")" aria-expanded="false" aria-controls="collapseExample">
                            More info
                        </button>
                    </p>
                    <div class="collapse" id="@item.Name.Replace(" ", "")">
                        <div class="card card-body" style="width: 18rem;">
                            <img src="~/img/@item.ImgUrl" class="card-img-top" />
                            <p class="card-text">@item.Details</p>
                        </div>
                    </div>
                </td>
            </tr>
        </tbody>

    }

</table>